# Generated by Django 2.1.5 on 2020-01-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
    ]
