# Generated by Django 2.1.5 on 2020-01-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200104_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('HGS', 'HYPE GREY SHIRT'), ('LRS', 'LONG RED SHIRT'), ('LRS', 'LONG SLEEVE JACKET'), ('DMS', 'DENIM MEN SHIRT')], max_length=50),
        ),
    ]
