# Generated by Django 2.1.5 on 2020-01-21 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200121_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_profile_picture',
            new_name='profile_picture',
        ),
    ]
