# Generated by Django 2.1.5 on 2020-01-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200104_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label_choices',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
